import { useEffect } from 'react';
import { Link, Route, Routes, useLocation, useParams } from 'react-router-dom';
import { ArrowRight, Check, Clock3, MapPin, MessageCircle, Phone, ShieldCheck, Truck, Wrench } from 'lucide-react';
import { phoneDisplay, phoneHref, whatsapp, cities, reviews, services } from './data';

const photoNames = ['tow-new-1.jpg','tow-new-2.jpg','tow-new-3.jpg','tow-new-4.jpg','tow-porsche.jpg','tow-van.jpg'];
const photo = (name:string) => `/images/${name}`;

function Seo({title,description}:{title:string;description:string}){
  useEffect(()=>{document.title=title;let m=document.querySelector('meta[name="description"]');if(!m){m=document.createElement('meta');m.setAttribute('name','description');document.head.appendChild(m)}m.setAttribute('content',description);},[title,description]);
  return null;
}

function Header(){return <header className="site-header"><div className="container header-inner"><Link to="/" className="brand"><span className="brand-mark">F</span><span><strong>FASTER</strong><small>DEPANNAGE & TAKELDIENST</small></span></Link><nav><a href="/#diensten">Diensten</a><a href="/#werkwijze">Werkwijze</a><a href="/#reviews">Reviews</a><Link to="/over-ons">Over ons</Link></nav><a className="header-phone" href={phoneHref}><Phone size={18}/><span>Bel {phoneDisplay}</span></a></div></header>}

function MobileBar(){return <div className="mobile-bar"><a href={phoneHref}><Phone size={19}/> Bel direct</a><a href={whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={19}/> WhatsApp</a></div>}

function Hero(){return <section className="hero"><div className="hero-media"><img src={photo('tow-new-1.jpg')} onError={e=>{e.currentTarget.style.opacity='0'}} alt="Takelwagen van Faster Depannage"/></div><div className="hero-shade"/><div className="container hero-content"><div className="eyebrow"><span className="dot"/> 24/7 bereikbaar vanuit Edegem</div><h1>Takeldienst die <em>komt opdagen.</em></h1><p className="hero-copy">Pech, ongeval of voertuigtransport? WhatsApp is het snelst. We luisteren naar wat er aan de hand is, geven duidelijk aan wat er nodig is en sturen hulp.</p><div className="cta-row"><a className="btn btn-ghost" href={whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={20}/> WhatsApp</a><a className="btn btn-primary" href={phoneHref}><Phone size={20}/> Bel direct <span>{phoneDisplay}</span></a></div><div className="trust-row"><span><ShieldCheck size={17}/> Verzekerd transport</span><span><Clock3 size={17}/> Dag & nacht bereikbaar</span><span><MapPin size={17}/> Antwerpen & omgeving</span></div></div></section>}

function ProofStrip(){return <section className="proof-strip"><div className="container proof-grid"><div><strong>24/7</strong><span>bereikbaar</span></div><div><strong>Eigen</strong><span>takelwagen</span></div><div><strong>Persoonlijk</strong><span>contact</span></div><div><strong>5★</strong><span>klantervaringen</span></div></div></section>}

function Services(){return <section id="diensten" className="section"><div className="container"><div className="section-head"><div><p className="kicker">Diensten</p><h2>Hulp wanneer je voertuig niet verder kan.</h2></div><p>Geen lange uitleg. Vertel ons wat er gebeurd is en waar je staat. We bekijken samen wat de beste oplossing is.</p></div><div className="service-grid">{services.map(([title,text],i)=><article className="service-card" key={title}><div className="service-num">0{i+1}</div><Wrench size={21}/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>}

function Work(){return <section id="werkwijze" className="section section-dark"><div className="container"><div className="split"><div><p className="kicker kicker-light">Zo werken we</p><h2>Van telefoontje naar oplossing.</h2><p className="lead">Bij pech wil je vooral weten wat er nu gebeurt. Daarom houden we het eenvoudig: WhatsApp is het snelst, bellen kan ook.</p></div><div className="steps">{[['01','Bel of WhatsApp','Vertel ons je locatie en wat er met het voertuig aan de hand is.'],['02','We spreken af','We bespreken wat nodig is en wat er met het voertuig gebeurt.'],['03','Wij regelen het','We komen ter plaatse of organiseren het juiste transport.']].map(([n,t,d])=><div className="step" key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}</div></div></div></section>}

function Gallery(){return <section className="section"><div className="container"><div className="section-head"><div><p className="kicker">Eigen werk</p><h2>Geen stockfoto's. Dit is Faster.</h2></div><p>Jouw bestaande foto's blijven een belangrijk onderdeel van de site: echt werk, echte voertuigen, echte opdrachten.</p></div><div className="gallery">{photoNames.map((p,i)=><figure key={p} className={i===0?'gallery-main':''}><img src={photo(p)} onError={e=>{e.currentTarget.style.opacity='0'}} alt="Werk van Faster Depannage"/><figcaption>Faster Depannage — eigen werk</figcaption></figure>)}</div></div></section>}

function Reviews(){return <section id="reviews" className="section section-muted"><div className="container"><div className="section-head center"><div><p className="kicker">Klantervaringen</p><h2>Wat klanten over Faster zeggen.</h2></div></div><div className="review-grid">{reviews.map(([name,text])=><article className="review" key={name}><div className="stars">★★★★★</div><p>“{text}”</p><strong>{name}</strong></article>)}</div></div></section>}

function Coverage(){return <section className="section"><div className="container coverage"><div><p className="kicker">Regio</p><h2>Van Edegem uit naar Antwerpen en omgeving.</h2><p>We zijn gevestigd in antwerpen en werken met een netwerk waarmee we klanten in en rond Antwerpen kunnen helpen. Voor internationale transporten bekijken we de opdracht apart.</p><a className="text-link" href={phoneHref}>Vraag hulp <ArrowRight size={17}/></a></div><div className="city-list">{cities.map(c=><Link to={c.slug === 'antwerpen' ? '/takeldienst-antwerpen/' : `/takeldienst/${c.slug}`} key={c.slug}>{c.name}<ArrowRight size={14}/></Link>)}</div></div></section>}

function Footer(){return <footer><div className="container footer-grid"><div><div className="brand brand-footer"><span className="brand-mark">F</span><span><strong>FASTER</strong><small>DEPANNAGE & TAKELDIENST</small></span></div><p>De Bosschaertstraat 248<br/>2020 Antwerpen (Kiel)</p></div><div><h3>Contact</h3><a href={phoneHref}>{phoneDisplay}</a><a href={whatsapp} target="_blank" rel="noreferrer">WhatsApp</a></div><div><h3>Diensten</h3><Link to="/takeldienst-antwerpen/">Takeldienst Antwerpen</Link><Link to="/#diensten">Pechverhelping</Link><Link to="/#diensten">Autotransport</Link></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Faster Depannage</span><span>Website onafhankelijk van Lovable beheerd</span></div></footer>}

function Home(){return <><Seo title="Takeldienst Faster | 24/7 Takeldienst Antwerpen" description="Faster Depannage vanuit Antwerpen. 24/7 takeldienst, pechverhelping en autotransport in Antwerpen en omgeving. WhatsApp of bel +32 3 375 67 37."/><Header/><main><Hero/><ProofStrip/><Services/><Work/><Gallery/><Reviews/><Coverage/><section className="final-cta"><div className="container"><p className="kicker">Hulp nodig?</p><h2>Staat je voertuig stil? Praat met Faster.</h2><div className="cta-row"><a className="btn btn-primary" href={phoneHref}><Phone size={20}/> {phoneDisplay}</a><a className="btn btn-light" href={whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={20}/> WhatsApp</a></div></div></section></main><Footer/><MobileBar/></>}

function About(){return <><Seo title="Over Faster Depannage | Takeldienst Edegem" description="Leer Faster Depannage kennen: een jonge, gedreven takeldienst uit Edegem met focus op snelheid, duidelijkheid en persoonlijke service."/><Header/><main><section className="page-hero"><div className="container"><p className="kicker">Over Faster</p><h1>Een takeldienst, geen callcenter.</h1><p>De nieuwe site wordt bewust eenvoudiger. Jij vertelt het probleem, wij luisteren, denken mee en regelen de oplossing.</p></div></section><section className="section"><div className="container narrow"><h2>Onze basis</h2><p>FASTER DEPANNAGE / TAKELDIENST is gevestigd in Edegem en helpt particulieren en bedrijven met takelen, pechverhelping en voertuigtransport.</p><p>De teksten op deze pagina zijn bewust als werkversie geschreven. Jouw eigen ervaringen, voorbeelden en manier van werken komen hier later centraal te staan.</p><div className="company-box"><div><MapPin size={20}/><strong>Boniverlei 172</strong><span>2650 Edegem</span></div><div><Truck size={20}/><strong>Eigen takelwagen</strong><span>Transport & berging</span></div><div><Phone size={20}/><strong>{phoneDisplay}</strong><span>24/7 contact</span></div></div><Link className="btn btn-primary" to="/">Terug naar home <ArrowRight size={18}/></Link></div></section></main><Footer/><MobileBar/></>}

function City(){const {slug}=useParams();const city=cities.find(c=>c.slug===slug)||cities[0];return <><Seo title={`Takeldienst ${city.name} | Faster Depannage`} description={`Takeldienst ${city.name} vanuit Edegem. 24/7 bereikbaar voor pechverhelping, takelen en autotransport. Bel ${phoneDisplay}.`}/><Header/><main><section className="page-hero city-page"><div className="container"><p className="kicker">Lokale service</p><h1>Takeldienst {city.name}</h1><p>Hulp bij pech, ongeval en voertuigtransport. Bel Faster en bespreek meteen wat er nodig is.</p><div className="cta-row"><a className="btn btn-primary" href={phoneHref}><Phone size={20}/> Bel {phoneDisplay}</a><a className="btn btn-light" href={whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={20}/> WhatsApp</a></div></div></section><section className="section"><div className="container coverage"><div><p className="kicker">Waarom Faster</p><h2>Duidelijke hulp, zonder omwegen.</h2><p>Voor elke interventie bekijken we de situatie: waar staat het voertuig, wat is er gebeurd en wat moet er gebeuren met het voertuig?</p></div><div className="side-box"><p><Check/> 24/7 bereikbaar</p><p><Check/> Persoonlijk contact</p><p><Check/> Eigen werk, echte foto's</p><p><Check/> Antwerpen en omgeving</p></div></div></section></main><Footer/><MobileBar/></>}

function NotFound(){return <><Header/><main className="not-found"><div className="container"><h1>Pagina niet gevonden.</h1><Link className="btn btn-primary" to="/">Terug naar Faster</Link></div></main></>}

export default function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/over-ons" element={<About/>}/><Route path="/takeldienst/:slug" element={<City/>}/><Route path="*" element={<NotFound/>}/></Routes>}
